/**
 * 012-payment-receipts: copy a picked file into the app's staging dir.
 *
 * After a successful pick + validation, the picker-owned temporary URI is
 * not guaranteed to survive the process lifecycle. We copy the file to
 * `<documentDir>/receipts/staging/<id>.<ext>` — a path we control and
 * that the uploader (running later, possibly in another session) can
 * find deterministically.
 *
 * The ID is the receipt ID generated by paymentReceiptsRepository, so the
 * staging path can be computed before the DB row exists.
 */

import * as FileSystem from 'expo-file-system/legacy';

import type { AttachmentMimeType } from '@/data/types';

const STAGING_DIR = `${FileSystem.documentDirectory ?? ''}receipts/staging/`;

function extensionFor(mime: AttachmentMimeType): string {
  switch (mime) {
    case 'image/jpeg':
      return 'jpg';
    case 'image/png':
      return 'png';
    case 'image/heic':
      return 'heic';
    case 'application/pdf':
      return 'pdf';
  }
}

async function ensureStagingDir(): Promise<void> {
  const info = await FileSystem.getInfoAsync(STAGING_DIR);
  if (!info.exists) {
    await FileSystem.makeDirectoryAsync(STAGING_DIR, { intermediates: true });
  }
}

export interface StageInput {
  receiptId: string;
  sourceUri: string;
  mimeType: AttachmentMimeType;
}

export interface StageOutput {
  /** Absolute path (without file:// prefix) for DB storage. */
  localPath: string;
  mimeType: AttachmentMimeType;
  sizeBytes: number;
}

/**
 * Copies `sourceUri` to the staging directory under a deterministic name
 * derived from `receiptId`. Returns the new local path along with the
 * stat'd size.
 *
 * Idempotent: if the target already exists (e.g. stage() called twice
 * for the same receipt), it is overwritten.
 */
export async function stage(input: StageInput): Promise<StageOutput> {
  await ensureStagingDir();

  const ext = extensionFor(input.mimeType);
  const destination = `${STAGING_DIR}${input.receiptId}.${ext}`;

  // Overwrite silently when a prior attempt left a file behind.
  const existing = await FileSystem.getInfoAsync(destination);
  if (existing.exists) {
    await FileSystem.deleteAsync(destination, { idempotent: true });
  }

  await FileSystem.copyAsync({ from: input.sourceUri, to: destination });

  const stat = await FileSystem.getInfoAsync(destination);
  const sizeBytes =
    stat.exists && typeof (stat as { size?: number }).size === 'number'
      ? (stat as { size: number }).size
      : 0;

  return {
    localPath: destination.replace(/^file:\/\//, ''),
    mimeType: input.mimeType,
    sizeBytes,
  };
}

export const __PATHS_ONLY__ = {
  STAGING_DIR,
  extensionFor,
};
